apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: k8s-demo
type: Opaque
data:
  api-key: dGhpcy1pcy1hLXNlY3JldC1hcGkta2V5 # this-is-a-secret-api-key
  db-connection: U2VydmVyPWxvY2FsaG9zdDtEYXRhYmFzZT1kYjtVc2VySWQ9cm9vdDtQYXNzd29yZD1zZWNyZXQ= # Server=localhost;Database=db;UserId=root;Password=secret